# Generated by Django 5.1 on 2024-08-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_board_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(default='images/defaultThumbnail.png', upload_to='images/'),
        ),
    ]
