# Generated by Django 5.1 on 2024-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_board_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(default='defaultThumbnail.png', upload_to='images/'),
        ),
    ]
