# Generated by Django 5.1 on 2025-03-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_board_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
