# Generated by Django 5.1 on 2025-03-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_board_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='id',
            new_name='board_id',
        ),
    ]
