# Generated by Django 5.1 on 2025-03-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_id_board_board_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_id',
            new_name='id',
        ),
    ]
