# Generated by Django 5.1 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_id',
            field=models.CharField(default='c154447a12edeb3ef2978cfa799389ab089bec95f87e7d0ebfc136d865cf6427', max_length=64),
        ),
    ]
