# Generated by Django 5.1 on 2025-03-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_board_board_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_id',
            new_name='user_id',
        ),
    ]
