# Generated by Django 5.1 on 2025-03-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_board_id_board_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='id',
            new_name='board_id',
        ),
    ]
