# Generated by Django 5.1 on 2025-04-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
