# Generated by Django 5.1 on 2025-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_board_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
