# Generated by Django 5.1 on 2025-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user_id',
        ),
    ]
