# Generated by Django 5.1 on 2025-04-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_board_user_id_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
