# Generated by Django 5.1 on 2025-04-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_create_at_board_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
    ]
